sample_timeout: 10
debug: False
api_url: '$TESTING_API_URL'
access_token: '$AUTH_TOKEN'
substitutions:
  '{version}': 'v1'
  '<ACCESS_TOKEN>': '$AUTH_TOKEN'
  'api-sandbox.lifeengine.io': '$TESTING_API_URL'

resp_attr_replacements:
  'product-api/products/{version}':
    - 'productCode': 'product_code'
  'identity-api/identities/v1':
    - '@id': 'id'
  'identity-api/identities/v1/{from_identity}/link/{to_identity}':
    - '@type': 'type'

before_sample:
  'identity-api/identities/v1/{from_identity}/link/{to_identity}':
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': 'to_identity'
    - resource: 'Identity'
      method: 'POST'
      subs:
        '@id': 'from_identity'
  'product-api/products/{version}':
    - resource: 'DeleteProduct'
      method: 'POST'
      subs: {}

ignore_failures:
  'broker-api/broker/{version}/fetch-data-product':
    - 'POST'
